### ISSUE TITLE
Thread panic when running `lake exe cache get`

### ISSUE THREAD

**Issue by pearapple123** [avigad/mathematics_in_lean_source#135]
Lean version: `Lean (version 4.0.0-nightly-2023-08-23, commit 216d2460e0ad, Release)`
Windows 11 Pro

This occurred when setting up the leanprover-community fork of this project.

Error:
```
info: downloading component 'lean'
179.9 MiB / 179.9 MiB (100 %)   5.0 MiB/s ETA:   0 s
info: installing component 'lean'
info: cloning https://github.com/leanprover-community/mathlib4 to .\lake-packages\mathlib
info: cloning https://github.com/leanprover/std4 to .\lake-packages\std
info: cloning https://github.com/gebner/quote4 to .\lake-packages\Qq
info: cloning https://github.com/JLimperg/aesop to .\lake-packages\aesop
info: cloning https://github.com/mhuisi/lean4-cli.git to .\lake-packages\Cli
info: cloning https://github.com/EdAyers/ProofWidgets4 to .\lake-packages\proofwidgets
info: Downloading proofwidgets/v0.0.13/windows-64.tar.gz
info: Unpacking proofwidgets/v0.0.13/windows-64.tar.gz
info: [1/9] Building Cache.IO
info: [2/9] Compiling Cache.IO
info: [2/9] Building Cache.Hashing
info: [3/9] Compiling Cache.Hashing
info: [3/9] Building Cache.Requests
info: [4/9] Compiling Cache.Requests
info: [4/9] Building Cache.Main
info: [7/9] Compiling Cache.Main
info: [9/9] Linking cache.exe
leantar is too old; downloading more recent version
Attempting to download 3678 file(s)
Downloaded: 3678 file(s) [attempted 3678/3678 = 100%] (100% success)
Decompressing 3678 file(s)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }', D:\a\leangz\leangz\src\ltar.rs:68:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }', D:\a\leangz\leangz\src\ltar.rs:68:53
uncaught exception: leantar failed with error code 101
```

**Comment by avigad** [comment]
This problem has nothing to do with this repository; it is happening when the Lean tooling tries to fetch and unpack the precompiled mathlib files. (I just managed to fetch and compile the repository on a Windows laptop without any problem.) 

When this happens, I usually try deleting the `lean-packages` directory and then running `lake exe cache get` again. If that doesn't work, I would ask about it on Zulip. Error messages like this come up every so often (see e.g. https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/leangz.20error/near/394537095) and someone might have a better idea how to fix it.
